---

antora:
  name: modules
  dir: www
  modules:
    - name: Step-01
      label: "Lab Login Info"
      solveButton: true
    - name: Step-02
      label: "Install USBGuard"
      solveButton: true
    - name: Step-03
      label: "Configure USBGuard"
    - name: Step-04
      label: "Verify USBGuard"
    - name: Step-05
      label: "Monitor USBGuard"
    - name: Step-06
      label: "Limitations of USBGuard"
    - name: Step-07
      label: "Real World Examples of USBGuard"
    - name: Step-08
      label: "Resources for USBGuard"

tabs:
  - name: ">_ terminal"
    url: /wetty_rhel/ssh/root
  - name: cockpit
    url: https://cockpit-${guid}.${domain}/
