# USBGuard Workshop Lab - RHEL 10

## Workshop Overview

This hands-on lab introduces USBGuard, a software framework for implementing USB device authorization policies on Linux systems. Learn to protect your RHEL 10 systems from unauthorized USB devices and potential security threats.

## Learning Objectives

By the end of this workshop, you will be able to:

* Understand USBGuard architecture and use cases
* Install and configure USBGuard on RHEL 10
* Create and manage USB device authorization policies
* Use USBGuard CLI tools to control device access
* Implement security policies for enterprise environments
* Troubleshoot common USBGuard issues

## Prerequisites

- Red Hat Enterprise Linux 10 system (physical or virtual)
- Root or sudo access
- Basic Linux command-line knowledge
- At least one USB device for testing


## Lab Environnement

You can use these credentials to login to the `cockpit` web ui.

Username:
[source,js]
----
rhel
----

Password:
[source,js,subs="+macros,+attributes",role=execute]
----
{bastion_ssh_password}
----

Enjoy your USBGuard lab time, the system will disconnect after about
60 minutes.

With the intro to USBGuard out of the way, lets head to the next step.

**Lab Note:** If Using Red Hat Demo System (RHPDS)
The terminal window to your right is already logged into the lab environment as the lab-user user via ssh. All steps of this lab are to be completed as the lab-user user on the bastion server.

When you follow the next steps, you will have instructions then a small box with text that is meant to be used in the terminal.
In the Upper Right Corner there will be a couple of symbols. It Should say something like "BASH", a icon of a clipboard, and an icon of a terminal.

You should also be able to click the terminal icon and the command is then auto typed into the machine terminal.

Alternatively, 

You should be able to click the clipboard icon in the code box to copy the command, and you will either use the middle mouse button or right click and paste. The keyboard shortcuts for copy and paste (ctrl+c and ctrl+v) wont’t work in this.

To Move to the next step, click the "Next" button.
